- name: setup mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: Installing mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
- name: update mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongodb.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: true
