- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Removing old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory





