- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Removing old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract {{ component }} content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes




